### PR TITLE
Add CI back to the project.

### PR DESCRIPTION
**Pull request by hugopl**

### CODE REVIEW

**Comment by hugopl** [comment]
failing because the project depends on libadwaita 1.2, only 1.1 is available in the github actions ubuntu image.

**Comment by micwoj92** [comment]
Now it is possible to specify `ubuntu-24.04`, which has 1.5.0 version of libadwaita.

**Comment by hugopl** [comment]
> Now it is possible to specify `ubuntu-24.04`, which has 1.5.0 version of libadwaita.

Thanks for remind me, I only had time to touch this today.

**Comment by hugopl** [comment]
oops, messed with the buttons, but now is merged :-)

**Pull request merged**
